# Generated by Django 4.0.2 on 2022-02-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='logo.png', null=True, upload_to='users/', verbose_name='프로필 이미지'),
        ),
    ]
