# Generated by Django 4.0.2 on 2022-02-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='users/', verbose_name='프로필 이미지'),
        ),
    ]
