# Generated by Django 4.0.2 on 2022-02-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='카테고리명')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='desc',
            field=models.CharField(default='desc', max_length=100, verbose_name='브랜드 소개'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='info',
            field=models.TextField(verbose_name='브랜드 설명'),
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.category', verbose_name='카테고리'),
        ),
    ]
