# Generated by Django 4.0.2 on 2022-02-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='태그명')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='tag',
            field=models.ManyToManyField(blank=True, to='brand.Tag', verbose_name='태그'),
        ),
    ]
