# Generated by Django 4.0.2 on 2022-02-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_category_brand_desc_alter_brand_info_brand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ko',
            field=models.CharField(default='패션', max_length=20, verbose_name='카테고리 한글명'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='카테고리 영문명'),
        ),
    ]
