# Generated by Django 4.0.2 on 2022-02-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_category_name_ko_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='영문 카테고리명'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ko',
            field=models.CharField(max_length=20, verbose_name='국문 카테고리명'),
        ),
    ]
