# Generated by Django 4.0.2 on 2022-02-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
